### ISSUE TITLE
[Bug]: Detach Console button broken

### ISSUE THREAD

**Issue by Sowgro** [AtomsDevs/Atoms#63]
### Describe the bug

```
Traceback (most recent call last):
  File "/app/share/atoms/atoms/views/dashboard.py", line 131, in __on_detach_clicked
    attach() if self.__detach_status else detach()
  File "/app/share/atoms/atoms/views/dashboard.py", line 125, in detach
    self.__detached_window = AtomsDetachedWindow(self.console, "#000000", title=self.atom.name)
  File "/app/share/atoms/atoms/windows/detached_window.py", line 35, in __init__
    self.__build_ui()
  File "/app/share/atoms/atoms/windows/detached_window.py", line 41, in __build_ui
    css_provider.load_from_data(str.encode(style))
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
```

### To Reproduce

Click the Detach Console button, the button will change to Attach Console, but no console will appear
Click Attach Console and nothing will happen

### Package

Flatpak from Flathub

### Distribution

Fedora 38

### Display Protocol

Wayland

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by mirkobrombin** [comment]
Thanks for reporting this. Atoms 2 replaced the old Python console and detached-window implementation, so this bug no longer applies.
